### ISSUE TITLE
Hide Sensitive data per view/widget

### ISSUE THREAD

**Issue by QuirijnGB** [uxcam/flutter-plugin#2]
Allow us to hide sensitive data on a smaller scale.

**Comment by Anup-UXCam** [comment]
Hi @QuirijnGB, thanks for the feedback. We are aware of this particular limitation and are going to be tackling this soon. In the meanwhile please see if our Blur API can be of some use. Thanks.

**Comment by DFDIEGOH** [comment]
Hi @QuirijnGB - We have released the new occlusion feature that allows you to hide sensitive data for specific widgets. [Here](https://developer.uxcam.com/docs/flutter-occlusion-feature) you will find the documentation for it but here you can also check the simplicity on how this gets implemented:

```
const OccludeWrapper(  
   child: Text(  
       'Sensitive data that will be occluded by the Wrapper',  
    ),  
),  
```
Feel free to contact team@uxcam.com in case you have any questions in this regard, really looking forward to get your feedback.
