### ISSUE TITLE
2.3.0 Memory leak

### ISSUE THREAD

**Issue by VusDanylo** [uxcam/flutter-plugin#28]
When I launch app and leave it running I have memory leak, that leads to crash in ~1 hour. I found that it is caused by 2.3.0 version of UXCam flutter plugin after calling `FlutterUxcam.startWithKey`. 
There are no leaks if `FlutterUxcam.startWithKey` was not called and if I change version to 2.2.2.

Screenshot from iOS leak instrument:
![image](https://user-images.githubusercontent.com/94787129/230072877-df3dd317-a389-4e92-984e-1bcd277f4bfc.png)
There are no such leaks in 2.2.2 version

Screenshot from Android profiler:
![image](https://user-images.githubusercontent.com/94787129/230073186-eaddb1b0-8bc6-451f-a637-125230775d9e.png)
Same but in 2.2.2 version:
![image](https://user-images.githubusercontent.com/94787129/230073312-fb304621-a1e3-4fec-ac94-d67a4362356f.png)

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.5, on macOS 13.0.1 22A400 darwin-arm64, locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by gabrieluxcam** [comment]
Hello @VusDanylo Gabriel here from UXCam. 

Thanks for bringing this up. I'm happy to let you know that we've fixed this on our end and will be releasing a fix with this next week. 

Also, feel free to keep an eye on our release page [here](https://help.uxcam.com/hc/en-us/articles/4404509626509--SDK-UPDATES) for any future changes.

Thanks!
