### ISSUE TITLE
Android session recordings is Black screen

### ISSUE THREAD

**Issue by engmsaleh** [uxcam/flutter-plugin#3]
Hi,
I have integrated flutter plugin into my flutter App. iOS recordings works fine, but Android is given blank screen
See screenshot below
 
![Screen Shot 2021-12-04 at 8 44 42 PM](https://user-images.githubusercontent.com/462150/144721004-bbeff642-d706-49ee-8cdd-cf379737bfa0.png)

Any advise

**Comment by luisfelipeas5** [comment]
This happened to me too!

**Comment by Anup-UXCam** [comment]
Hi, please create a new issue if you find this again, thanks.
