### ISSUE TITLE
Android build error 

### ISSUE THREAD

**Issue by ocastx** [uxcam/flutter-plugin#8]
Last version update (2.1.3) seems to break Android builds. 

<img width="1239" alt="CleanShot 2022-09-05 at 19 09 36@2x" src="https://user-images.githubusercontent.com/2399622/188493508-801fca67-45e3-41ee-bf81-5a9e2452d612.png">

**Comment by Anup-UXCam** [comment]
Hi @ocastx , please check the new version and apologies for late response.
